FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.11 AS base

RUN apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = false

EXPOSE 80
EXPOSE 443

WORKDIR /app


FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.11 AS build
WORKDIR /src
COPY ["TaxaJuros/TaxaJuros.Api/TaxaJuros.Api.csproj", ""]
RUN dotnet restore "TaxaJuros.Api.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "TaxaJuros/TaxaJuros.Api/TaxaJuros.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TaxaJuros/TaxaJuros.Api/TaxaJuros.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaxaJuros.Api.dll"]